// register
export const STUDENT_REGISTRATION_INIT="STUDENT_REGISTRATION_INIT";
export const STUDENT_REGISTRATION_SUCCESS="STUDENT_REGISTRATION_SUCCESS";
export const STUDENT_REGISTRATION_FAILURE="STUDENT_REGISTRATION_FAILURE";

// login
export const STUDENT_LOGIN_INIT="STUDENT_LOGIN_INIT";
export const STUDENT_LOGIN_SUCCESS="STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAILURE="STUDENT_LOGIN_FAILURE";

// logout
export const STUDENT_LOGOUT = "STUDENT_LOGOUT";