// register
export const TEACHER_REGISTRATION_INIT="TEACHER_REGISTRATION_INIT";
export const TEACHER_REGISTRATION_SUCCESS="TEACHER_REGISTRATION_SUCCESS";
export const TEACHER_REGISTRATION_FAILURE="TEACHER_REGISTRATION_FAILURE";


// login
export const TEACHER_LOGIN_INIT="TEACHER_LOGIN_INIT";
export const TEACHER_LOGIN_SUCCESS="TEACHER_LOGIN_SUCCESS";
export const TEACHER_LOGIN_FAILURE="TEACHER_LOGIN_FAILURE";

// logout
export const TEACHER_LOGOUT = "TEACHER_LOGOUT";